test_project/items/urls.py
from django.urls import path
from . import views

app_name = "items"
urlpatterns = [
    # return all items
    path('', views.index, name='index'), 

    # filter items using a query parameter
    path('<str:name>', views.get_itemsparam, name='index'),

    # add item
    path('add/<str:id>', views.add_item, name='index'),

    # get item
    path('<int:id>/', views.get_items, name='index'),

    # update item
    path('update/<int:id>/', views.update_item, name='index'),

    # delete item
    path('delete/<int:id>/', views.delete_item, name='index'),
]

test_project/portfolio/urls.py
from django.urls import path 
from .views import index 
from .views import portfolio
from .views import dashboard

app_name = "portfolio"
urlpatterns = [  
    path( 'portfolio/', portfolio, name='portfolio'),
    path( '', index, name='index'),
    path( 'dashboard/', dashboard, name='dashboard'),
] 

test_project/test_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls', namespace="portfolio")),
    path('api/', include([
        path('users/', include('users.urls', namespace='users')),
    ])),
    path('api/', include([
        path('items/', include('items.urls', namespace='items')),
    ])),
]



test_project/users/urls.py
from django.urls import path
from .views import index, get_users, create_user

app_name = "users"
urlpatterns = [
    path('', index, name='index'),
    path('<str:id>', get_users, name='index'),
    path('add/<str:id>', create_user, name='index'),
]

test_project/items/models.py
from django.db import models

# Create your models here.

test_project/portfolio/models.py
from django.db import models

# Create your models here.

test_project/items/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET
from django.views.decorators.http import require_http_methods

# Create your views here.
@require_GET
def index(request):
    data = {
        "item_name": "mouse",
        "price": 120
    }
    return JsonResponse({"message": "success", "payload": data}, status=200)

def get_itemsparam(request):

    # query param users/2?user=[name]
    payload = request.GET

    data = {
        "context": payload,
    }
    return JsonResponse({"message": "success", "payload": data}, status=200)







@require_POST
@csrf_exempt

def add_item(request, id):
    payload = request.GET
    data = {
        "id": id,
        "context": payload,
    }
    return JsonResponse({"message": "success", "payload": data}, status=200)

@require_GET
def get_items(request, id):
    payload = request.GET
    data = {
        "id": 10,
        "item_name": "mouse",
        "price": 120,
    }
    return JsonResponse({"message": "success", "payload": data}, status=200)

@require_http_methods(["PUT"])
@csrf_exempt
def update_item(request, id):
    payload = request.GET
    data = {
        "id": 10,
        "item_name": "mouse",
        "price": 120,
    }
    return JsonResponse({"message": "success", "payload": data}, status=200)

@require_http_methods(["DELETE"])
@csrf_exempt
def delete_item(request, id):
    payload = request.GET
    data = {
        "id": 10,
        "item_name": "mouse",
        "price": 120,
    }
    return JsonResponse({"message": "success", "payload": data}, status=200)

test_project/portfolio/views.py
from django.shortcuts import render

# Create your views here.
def index(request): 
    return render(request, "pages/index.html") 

def portfolio(request): 
    return render(request, "pages/portfolio.html") 

def dashboard(request):
    data = [
        {"title": "Users", "count": 150},
        {"title": "Orders", "count": 320},
        {"title": "Revenue", "count": "12450"},
    ]
    return render(request, "pages/dashboard.html", context={"data": data})


test_project/users/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET

# Create your views here.
@require_GET
def index(request):
    data = {
        "title": "Users",
        "count": 120
    }
    return JsonResponse({"message": "success", "payload": data}, status=200)

@require_POST
@csrf_exempt

def create_user(request, id):
    payload = request.GET
    data = {
        "id": id,
        "context": payload,
    }
    return JsonResponse({"message": "success", "payload": data}, status=200)

def get_users(request, id):

    # query param users/2?user=[name]
    payload = request.GET

    data = {
        "id": id,
        "context": payload,
    }
    return JsonResponse({"message": "success", "payload": data}, status=200)

test_project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'dashboard.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    
<div class="d-flex" id="wrapper">
    <div class="sidebar" id="sidebar-wrapper" style="position: fixed; height: 100vh; width: 250px;">
        <div class="sidebar-heading text-center py-4 primary-text fs-5 fw-bold border-bottom">Activity 2</div>
        <div class="list-group list-group-flush my-1">
            <a href="{% url 'portfolio:dashboard' %}" class="list-group-item list-group-item-action bg-transparent second-text active">
                <i class="fas fa-tachometer-alt me-2"></i>Dashboard</a>
            <a href="{% url 'portfolio:portfolio' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                <i class='bx bxs-file me-2'></i>Profile</a>
        </div>
    </div>

    <div id="page-content-wrapper" style="margin-left: 250px; width: calc(100% - 250px);">
        <nav class="navbar navbar-expand-lg navbar-light py-4 px-4">
            <div class="d-flex align-items-center">
                <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
                <h2 class="fs-2 m-0">Dashboard</h2>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <div class="nav-link dropdown-toggle second-text fw-bold" id="navbarDropdown">
                            Admin
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        {% block body %}{% endblock %}
    </div>
</div>
</body>
</html>

test_project/templates/pages/dashboard.html
{% extends "base.html" %}
{% load stat %}
{% load static %}

{% block title %}
    Dashboard
{% endblock %}

{% block body %}
<div class="container mx-auto p-4">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {% for item in data %}
        <div class="bg-white shadow-md p-6 hover:shadow-lg transition-shadow duration-300 rounded-lg">
          <h2 class="text-xl font-semibold mb-2">{{ item.title }}</h2>
          <p class="text-4xl font-bold text-gray-800">{{ item.count|format_count }}</p>
        </div>
      {% endfor %}
    </div>
  </div>
  
  <div class="try_image">
    <img src="{%static 'profile_pic.jpg'%}" alt="">
  </div>

 
{% endblock %}

test_project/templates/pages/index.html
{% load static %}


<!DOCTYPE html> 
<html lang="en"> 
<head> 
<meta charset="UTF-8"> 
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<link rel="stylesheet" href="{% static 'style.css' %}" />
<title>Portfolio</title> 
</head> 
<body> 
<!-- <img src="{% static 'turtle_bg.jpg' %}" /> -->
<div class="main-page">
    <h1>My Simple Portfolio</h1>
    <h2>My Simple Portfolio</h2>
    <!-- <h3>explore my portfolio!</h3> -->
    <a href="{% url 'portfolio:portfolio'%}" class="wooden-link">Portfolio</a>
    <a href="{% url 'portfolio:dashboard'%}" class="wooden-link">Dashboard</a>
</div>

</body> 
</html> 

test_project/templates/pages/portfolio.html
{% load static %}


<!DOCTYPE html> 
<html lang="en"> 
<head> 
<meta charset="UTF-8"> 
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<link rel="stylesheet" href="{% static 'style.css' %}" />
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
<title>Portfolio</title> 
</head> 
<body> 

    <nav>
        <ul>
            <li><a href="#profile-section">Skills</a></li>
            <li><a href="#projects-section">Project</a></li>
            <li><a href="#contacts-section">Contact</a></li>
            <li><a href="{% url 'portfolio:dashboard' %}">Dashboard</a></li>
        </ul>
    </nav>

    <div class="main-page">
        <h1>My Simple Portfolio</h1>
        <h2>My Simple Portfolio</h2>
        <!-- <h3>explore my portfolio!</h3> -->
        <a href="#profile-section" class="wooden-link">EXPLORE</a>
    </div>
<!-- <img src="{% static 'turtle_bg.jpg' %}" /> -->

    <section class="profile-section" id="profile-section">
        <div class="profile">
            <img src="{% static 'profile_pic.jpg' %}" />
        </div>
        <div class="profile-desc">
            <p>Hi! I'm Vinz Reibhen Ilagan</p>
            <h4>A BSIT student from Gordon College, who is passionate about web development</h4>
        </div>
        <div class="dev-skill">
            <h3>My Skills</h3>
            <ul>
                <li> <i class='bx bxl-html5 bx-tada' style="color: rgb(255, 123, 0);"></i> HTML</li>
                <li> <i class='bx bxl-css3 bx-tada' style="color: #1d84fa;" ></i> CSS</li>
                <li> <i class='bx bxl-javascript bx-tada' style="color: rgb(170, 255, 0);" ></i> JavaScript</li>
                <li> <i class='bx bxl-python bx-tada' style='color:#04b4e9' ></i> Python</li>
                <li> <i class='bx bxl-django bx-tada' style='color:#336329'  ></i> Django</li>
            </ul>
        </div>
    </section>

    <section class="project-section" id="projects-section">
        <h3>My Project</h3>
        <div class="project">
            <div class="project-img">
                <div class="select1">
                    <img src="{% static 'gc_proco1.png' %}" class="gc_proco1" />
                </div>

                <div class="select2">
                    <img src="{% static 'gc_proco2.png' %}" class="gc_proco2"/>
                </div>
                
            </div>
            <h4>GC ProCo</h4>
            <p>I am currently working on a project and task management web-app for BSIT students of Gordon College</p>
        </div>

    </section>

    <section class="contact-section" id="contacts-section">
        <h3>Contact Me</h3>
        <p class="contact-description">Feel free to reach out via email, phone, or social media. I look forward to hearing from you!</p>
        <div class="contact">
            <div class="contact-info">
                <i class="fas fa-envelope"></i>
                <h4>Email</h4>
                <p>vinzreibhen@gmail.com</p>
            </div>
            <div class="contact-info">
                <i class="fas fa-phone-alt"></i>
                <h4>Phone</h4>
                <p>09183061804</p>
            </div>
            <div class="contact-info">
                <i class="fab fa-facebook"></i>
                <h4>Social Media</h4>
                <p>Facebook: Vinz Ilagan</p>
                <p>Instagram: @tilaplapya</p>
            </div>
        </div>
        <form class="contact-form">
            <h4>Send a Message</h4>
            <input type="text" placeholder="Your Name" required>
            <input type="email" placeholder="Your Email" required>
            <textarea placeholder="Your Message" required></textarea>
            <button type="submit">Send Message</button>
        </form>
        <div class="map">
            <h4>Find Me Here!</h4>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7721.309689139934!2d120.28287204323693!3d14.831717702991248!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x339671bfbd44a7b7%3A0x52e5f5bb9f1b63b4!2sOlongapo%20City%2C%20Zambales%2C%20Philippines!5e0!3m2!1sen!2sph!4v1708000000000!5m2!1sen!2sph" width="100%" height="250" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
    </section>
</body> 


</html> 